### ISSUE TITLE
Avoid explosion of `From` implementations?

### ISSUE THREAD

**Issue by jkorinth** [cofibrant/obake#13]
I played around a bit and noticed that every new version of a struct seems to require a `From` implementation for every previous version, instead of only its immediate predecessor. After a few versions, this will require quite a lot of error-prone boilerplate. In theory, the versions are unique and totally ordered, so it should be sufficient to provide a `From` implementation from the most recent version to the new one, no?

**Comment by doctorn** [comment]
It should be the case that you only need a from implementation from the directly previous version. If this is not the case, this is a bug.

**Comment by dlight** [comment]
Ideally Obake should be able to generate `From` instances through some syntax like `#[obake(version("0.1.2"), derive(From))` or something like that... at least in the common case where you add a new field with a default value. (you would need something like a `#[default]` in new fields, like done in serde)

(I actually planned to eventually implement this but never got the chance)

**Comment by jkorinth** [comment]
Tried but couldn't reproduce the issue any more. If it pops up again, I'll let you know.
